### ISSUE TITLE
Erro ao executar comando /baixar {tiktok_link}

### ISSUE THREAD

**Issue by thel3onardo** [luisgbr1el/kelle-telegram#2]
A requisição download.tiktok(url) - (linha 32), feita após o usuário digitar o comando 'baixar',  está falhando com status 500. Com essa falha, o programa deixa de ser executado e, basicamente, o bot morre.

![image](https://user-images.githubusercontent.com/79659551/150832068-b7687715-c900-47a8-a240-89223e958c33.png)

**Comment by luisgbr1el** [comment]
@thel3onardo Aqui funciona normalmente, já tentou reinstalar as *packages* ou atualizar seu *Node.js*?
